name: flutter_application_1
description: Aplikasi Resep Makanan dengan Planner
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.5
  
  # HTTP & API
  http: ^0.13.5
  
  # State Management
  provider: ^6.0.5
  
  # Video Player
  video_player: ^2.6.1
  chewie: ^1.4.0
  
  # Notifications
  flutter_local_notifications: ^14.0.0
  timezone: ^0.9.1
  
  # URL Launcher
  url_launcher: ^6.1.9
  
  # Date & Time Formatting
  intl: ^0.18.1
  
  # Local Storage
  shared_preferences: ^2.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true